Handling dynamic device changes
Ckath/mergeinputs pull request #9
Opened 2023-04-27 16:36 UTC by mreiger

Hi I found a way to handle device changes (ie hotplugging of keyboards) by watching the path where mergeinputs gets its devices and restarting the service if there are any changes.

Luckily the virtual input device that mergeinputs creates gets no entry in the `by-id` subdirectory, so this seems safe and should not create loops.

2023-04-28 07:55 UTC, mreiger commented
Hang on; this fails when no (external) keyboards are connected. Gonna try and fix that.

2023-04-28 08:27 UTC, mreiger commented
Should be fixed now.

2023-05-18 13:52 UTC, Ckath commented
first sorry for the late response havent been getting to notifications lately
secondly seems like a good idea to throw it into the services, like that a lot better than having to deal with it in the program. one small petpeeve when this is combined with my awful setup is that I have mutliple devices with the same ids. with the restart limits set it seems to not endlessly loop with by-path either so it should be fine regardless.

nice find though did not look into system for watching changes in a path

2023-05-18 13:55 UTC, Ckath requested changes
if you feel like it otherwise I'll correct it after merge in a week or so. again good job finding it
cheers

2023-05-18 13:55 UTC, Ckath commented on mergeinputs-restart.path
> +PathChanged=/dev/input/by-id
this works with `by-path` as well

2023-05-18 13:55 UTC, Ckath commented on mergeinputs.service
> +ConditionPathExistsGlob=/dev/input/by-id/*-kbd
though it doesnt really effect this case, might as well use `by-path` here too

2023-05-18 13:55 UTC, Ckath commented on mergeinputs.service
>  ExecStart=/bin/sh -c '/usr/local/bin/mergeinputs /dev/input/by-id/*-kbd'
and here a `by-path` makes it work again for my stuff

2023-05-24 15:19 UTC, mreiger commented
`by-path` works for me just as well as `by-id`, so there's no problem for me to change it.

Interestingly I have a third `*kbd` device in `by-path` in addition to the two halves of my split keyboard. Merging all three together seems to have no adverse effects.

2023-05-25 17:35 UTC, Ckath commented
great stuff, cheers for looking into it and implementing it with sytemd services.

2023-05-25 17:36 UTC, merged